---
- name: update Cisco login banner
  hosts: all
  connection: local
  
  vars:
    ciscoios: 'cisco_ios'
    ciscoiosssh: 'cisco_ios_ssh'
    
  tasks:
  
  - name: configure the login banner
    ios_banner:
      banner: login
      text: |
        this is my login banner
        that contains a multiline
        string
      state: present

  - name: remove the motd banner
    ios_banner:
      banner: motd
      state: absent
       
  - name: Configure banner from file
    ios_banner:
      banner:  motd
      text: "{{ lookup('file', './banner.txt') }}"
      state: present
