---
- name: set enable password
  hosts: all
  connection: local
    
  tasks: 

  - name: set secret password
    ios_config:
      lines: enable secret 5 $1$lyq2$DLhnBnmb103ohI/pqIHS20
       
  - name: remove week password
    ios_command:
      commands:  'no enable password'
      
  - name: save config
    ios_command:
      commands:  'write mem'
   