---
- name: configure system logging
  hosts: all
  connection: local
    
  tasks: 

  - name: ensure logging is on
    ios_logging:
      dest: on
      state: present
      
  - name: configure logging host 1
    ios_logging:
      dest: host
      name: 10.224.114.71
      level: informational
      state: present
      
  - name: configure logging host 2
    ios_logging:
      dest: host
      name: 10.224.115.31
      level: informational
      state: present
 
  - name: configure console logging
    ios_logging:
      dest: console
      level: informational
      state: present
      
  - name: configure vty line logging
    ios_logging:
      dest: monitor
      level: informational
      state: present
      
  - name: configure buffered logging
    ios_logging:
      dest: buffered
      level: informational
      size: 64000
      state: present
      
  - name: save config
    ios_config:
      save_when: always
   