---
- name: STIG BASELINE COMPLIANCE
  hosts: all
  connection: local
    
  tasks:
  

  - name: configure services
    ios_config:
      lines:
        - service password-encryption
        # - service tcp-keepalives-in
        # - service tcp-keepalives-out
        # - service timestamps debug datetime msec
        # - service timestamps log datetime msec
        # - service linenumber
        # - no service pad
        # - no service finger
        # - no service udp-small-servers
        # - no service tcp-small-servers
        # - no boot network
        # - no service config
        # - no service pad
        # - no ip rcmd rcp-enable
        # - no ip rcmd rsh-enable
        # - no ip http server
        # - no ip http secure-server
       
  # - name: Configure Time
    # ios_config:
        # lines:
      #   - clock timezone utc 0 0
      #   - ntp update-calendar
      #   - ntp server 10.224.1.16 prefer
      #   - ntp server 10.224.1.17
      #   - ntp server 10.224.225.5
      #   - ntp server 10.224.225.6
      #   - clock timezone UTC 0 0
      #   - no clock summer-time 
      
  # - name: Configure IP settings
    # ios_config:
        # lines:
      #   - ip subnet-zero
      #   - no ip source-route
      #   - no ip gratuitous-arps
      #   - no ip directed-broadcast
      #   - no ip domain-lookup
      #   - no ip bootp server
      #   - ip tcp synwait-time 10
      #   - ip tcp intercept connection-timeout 60
      #   - ip tcp intercept watch-timeout 10
      #   - ip ssh authentication-retries 2
      
  # - name: SNMP
    # ios_config:
        # lines:
      #   - no snmp-server system-shutdown
      #   - no snmp-server community public RO
      #   - no snmp-server community private RW
      
  # - name: CNS
    # ios_config:
        # lines:
      #   - no diagnostic cns publish
      #   - no diagnostic cns subscribe
      
  # - name: vstack
    # ios_config:
        # lines:
      #   - no vstack config
      #   - no vstack
      
  # - name: SSH
    # ios_config:
        # lines:
      #   - ip ssh time-out 60
      #   - ip ssh version 2
      #   - ip ssh authentication-retries 3
      #   - ip scp server enable
      
  # - name: VTY lines
    # ios_config:
        # lines:
      #   - exec-timeout 10 0
      #   - logging synchronous
    # parents: 
      # - line vty 0 4
      # - line vty 5 15