---
- name: STIG BASELINE COMPLIANCE
  hosts: all
  connection: local
    
  tasks:
  
##### SERVICES #####

  # - name: password-encryption
    # ios_config:
      # lines: service password-encryption
    # ignore_errors: yes

  # - name: tcp-keepalives-in
    # ios_config:
      # lines: service tcp-keepalives-in
    # ignore_errors: yes
    
  # - name: tcp-keepalives-out
    # ios_config:
      # lines: service tcp-keepalives-out
    # ignore_errors: yes
    
  # - name: timestamps debug
    # ios_config:
      # lines: service timestamps debug datetime msec
    # ignore_errors: yes
    
  # - name: timestamps log
    # ios_config:
      # lines: service timestamps log datetime msec
    # ignore_errors: yes
    
  # - name: service linenumber
    # ios_config:
      # lines: service linenumber
    # ignore_errors: yes
    
  # - name: network boot
    # ios_config:
      # lines: no boot network
    # ignore_errors: yes
        
  # - name: pad
    # ios_config:
      # lines: no service pad
    # ignore_errors: yes
    
  # - name: finger
    # ios_config:
      # lines: no service finger
    # ignore_errors: yes

  # - name: udp servers
    # ios_config:
      # lines: no service udp-small-servers
    # ignore_errors: yes

  # - name: tcp servers
    # ios_config:
      # lines: no service tcp-small-servers
    # ignore_errors: yes

  # - name: service config
    # ios_config:
      # lines: no service config
    # ignore_errors: yes

  # - name: rcp
    # ios_config:
      # lines: no ip rcmd rcp-enable
    # ignore_errors: yes

  # - name: rsh
    # ios_config:
      # lines: no ip rcmd rsh-enable
    # ignore_errors: yes

  # - name: http
    # ios_config:
      # lines: no ip http server
    # ignore_errors: yes

  # - name: https
    # ios_config:
      # lines: no ip http secure-server
    # ignore_errors: yes
      
##### SYSTEM TIME #####

  - name: UTC timezone
    ios_config: 
        lines: clock timezone utc 0 0 
    ignore_errors: yes

  - name: update-calendar
    ios_config:
      lines: ntp update-calendar
    ignore_errors: yes

  - name: ntp server 1
    ios_config:
      lines: ntp server 10.224.1.16 prefer
    ignore_errors: yes

  - name: ntp server 2
    ios_config:
      lines: ntp server 10.224.1.17
    ignore_errors: yes

  - name: ntp server 3
    ios_config:
      lines: ntp server 10.224.225.5
    ignore_errors: yes

  - name: ntp server 4
    ios_config:
      lines: ntp server 10.224.225.6
    ignore_errors: yes

  - name: daylight savings
    ios_config:
      lines: no clock summer-time
    ignore_errors: yes

     
  # - name: Configure IP settings
    # ios_config:
        # lines:
      #   - ip subnet-zero
      #   - no ip source-route
      #   - no ip gratuitous-arps
      #   - no ip directed-broadcast
      #   - no ip domain-lookup
      #   - no ip bootp server
      #   - ip tcp synwait-time 10
      #   - ip tcp intercept connection-timeout 60
      #   - ip tcp intercept watch-timeout 10
      #   - ip ssh authentication-retries 2
      
  # - name: SNMP
    # ios_config:
        # lines:
      #   - no snmp-server system-shutdown
      #   - no snmp-server community public RO
      #   - no snmp-server community private RW
      
  # - name: CNS
    # ios_config:
        # lines:
      #   - no diagnostic cns publish
      #   - no diagnostic cns subscribe
      
  # - name: vstack
    # ios_config:
        # lines:
      #   - no vstack config
      #   - no vstack
      
  # - name: SSH
    # ios_config:
        # lines:
      #   - ip ssh time-out 60
      #   - ip ssh version 2
      #   - ip ssh authentication-retries 3
      #   - ip scp server enable
      
  # - name: VTY lines
    # ios_config:
        # lines:
      #   - exec-timeout 10 0
      #   - logging synchronous
    # parents: 
      # - line vty 0 4
      # - line vty 5 15
      
