---
- name: STIG BASELINE COMPLIANCE
  hosts: all
  connection: local
    
  tasks:
  

  - name: configure services
    ios_config:
      lines: service password-encryption
      lines: service tcp-keepalives-in
      lines: service tcp-keepalives-out
      lines: service timestamps debug datetime msec
      lines: service timestamps log datetime msec
      lines: service linenumber
      lines: no service pad
      lines: no service finger
      lines: no service udp-small-servers
      lines: no service tcp-small-servers
      lines: no boot network
      lines: no service config
      lines: no service pad
      lines: no ip rcmd rcp-enable
      lines: no ip rcmd rsh-enable
      lines: no ip http server
      lines: no ip http secure-server
      state: present
       
  # - name: Configure Time
    # ios_config:
      # lines: clock timezone utc 0 0
      # lines: ntp update-calendar
      # lines: ntp server 10.224.1.16 prefer
      # lines: ntp server 10.224.1.17
      # lines: ntp server 10.224.225.5
      # lines: ntp server 10.224.225.6
      # lines: clock timezone UTC 0 0
      # lines: no clock summer-time 
      # state: present
      
  # - name: Configure IP settings
    # ios_config:
      # lines: ip subnet-zero
      # lines: no ip source-route
      # lines: no ip gratuitous-arps
      # lines: no ip directed-broadcast
      # lines: no ip domain-lookup
      # lines: no ip bootp server
      # lines: ip tcp synwait-time 10
      # lines: ip tcp intercept connection-timeout 60
      # lines: ip tcp intercept watch-timeout 10
      # lines: ip ssh authentication-retries 2
      # state: present
      
  # - name: SNMP
    # ios_config:
      # lines: no snmp-server system-shutdown
      # lines: no snmp-server community public RO
      # lines: no snmp-server community private RW
      # state: present
      
  # - name: CNS
    # ios_config:
      # lines: no diagnostic cns publish
      # lines: no diagnostic cns subscribe
      # state: present
      
  # - name: vstack
    # ios_config:
      # lines: no vstack config
      # lines: no vstack
      # state: present
      
  # - name: SSH
    # ios_config:
      # lines: ip ssh time-out 60
      # lines: ip ssh version 2
      # lines: ip ssh authentication-retries 3
      # lines: ip scp server enable
      # state: present
      
  # - name: VTY lines
    # ios_config:
      # lines: exec-timeout 10 0
      # lines: logging synchronous
    # parents: 
      # - line vty 0 4
      # - line vty 5 15