---
- name: STIG BASELINE COMPLIANCE
  hosts: all
  connection: local
    
  tasks:
  
##### SERVICES #####

  # - name: password-encryption
    # ios_config:
      # lines: service password-encryption
    # ignore_errors: yes

  # - name: tcp-keepalives-in
    # ios_config:
      # lines: service tcp-keepalives-in
    # ignore_errors: yes
    
  # - name: tcp-keepalives-out
    # ios_config:
      # lines: service tcp-keepalives-out
    # ignore_errors: yes
    
  # - name: timestamps debug
    # ios_config:
      # lines: service timestamps debug datetime msec
    # ignore_errors: yes
    
  # - name: timestamps log
    # ios_config:
      # lines: service timestamps log datetime msec
    # ignore_errors: yes
    
  # - name: service linenumber
    # ios_config:
      # lines: service linenumber
    # ignore_errors: yes
    
  # - name: network boot
    # ios_config:
      # lines: no boot network
    # ignore_errors: yes
        
  # - name: pad
    # ios_config:
      # lines: no service pad
    # ignore_errors: yes
    
  # - name: finger
    # ios_config:
      # lines: no service finger
    # ignore_errors: yes

  # - name: udp servers
    # ios_config:
      # lines: no service udp-small-servers
    # ignore_errors: yes

  # - name: tcp servers
    # ios_config:
      # lines: no service tcp-small-servers
    # ignore_errors: yes

  # - name: service config
    # ios_config:
      # lines: no service config
    # ignore_errors: yes

  # - name: rcp
    # ios_config:
      # lines: no ip rcmd rcp-enable
    # ignore_errors: yes

  # - name: rsh
    # ios_config:
      # lines: no ip rcmd rsh-enable
    # ignore_errors: yes

  # - name: http
    # ios_config:
      # lines: no ip http server
    # ignore_errors: yes

  # - name: https
    # ios_config:
      # lines: no ip http secure-server
    # ignore_errors: yes
      
##### SYSTEM TIME #####

  # - name: UTC timezone
    # ios_config: 
        # lines: clock timezone utc 0 0 
    # ignore_errors: yes

  # - name: update-calendar
    # ios_config:
      # lines: ntp update-calendar
    # ignore_errors: yes

  # - name: ntp server 1
    # ios_config:
      # lines: ntp server 10.224.1.16 prefer
    # ignore_errors: yes

  # - name: ntp server 2
    # ios_config:
      # lines: ntp server 10.224.1.17
    # ignore_errors: yes

  # - name: ntp server 3
    # ios_config:
      # lines: ntp server 10.224.225.5
    # ignore_errors: yes

  # - name: ntp server 4
    # ios_config:
      # lines: ntp server 10.224.225.6
    # ignore_errors: yes

  # - name: daylight savings
    # ios_config:
      # lines: no clock summer-time
    # ignore_errors: yes

##### IP SETTINGS #####

  # - name: subnet zero
    # ios_config:
        # lines: ip subnet-zero
    # ignore_errors: yes      

  # - name: source-route
    # ios_config:
      # lines: no ip source-route
    # ignore_errors: yes

  # - name: gratuitous-arps
    # ios_config:
      # lines: no ip gratuitous-arps
    # ignore_errors: yes

  # - name: directed-broadcast
    # ios_config:
      # lines: no ip directed-broadcast
    # ignore_errors: yes

  # - name: domain-lookup
    # ios_config:
      # lines: no ip domain-lookup
    # ignore_errors: yes

  # - name: bootp
    # ios_config:
      # lines: no ip bootp server
    # ignore_errors: yes

  # - name: synwait-time
    # ios_config:
      # lines: ip tcp synwait-time 10
    # ignore_errors: yes

  # - name: tcp intercept connection
    # ios_config:
      # lines: ip tcp intercept connection-timeout 60
    # ignore_errors: yes

  # - name: tcp intercept watch
    # ios_config:
      # lines: ip tcp intercept watch-timeout 10
    # ignore_errors: yes

  # - name: authentication-retries
    # ios_config:
      # lines: ip ssh authentication-retries 2
    # ignore_errors: yes

##### SNMP #####

  - name: SNMP shutdown
    ios_config:
        lines: no snmp-server system-shutdown
    ignore_errors: yes
    
  - name: SNMP community public
    ios_config:
      lines: no snmp-server community public RO
    ignore_errors: yes
    
  - name: SNMP community private
    ios_config:
      lines: no snmp-server community private RW
    ignore_errors: yes
    
  # - name: CNS
    # ios_config:
        # lines:
      #   - no diagnostic cns publish
      #   - no diagnostic cns subscribe
      
  # - name: vstack
    # ios_config:
        # lines:
      #   - no vstack config
      #   - no vstack
      
  # - name: SSH
    # ios_config:
        # lines:
      #   - ip ssh time-out 60
      #   - ip ssh version 2
      #   - ip ssh authentication-retries 3
      #   - ip scp server enable
      
  # - name: VTY lines
    # ios_config:
        # lines:
      #   - exec-timeout 10 0
      #   - logging synchronous
    # parents: 
      # - line vty 0 4
      # - line vty 5 15
      
